os:
  editCommand: "nvr -cc 'split | only' --remote-wait +'set bufhidden=delete'"
customCommands:
  - key: "S"
    description: "spin-off"
    prompts:
      - type: "input"
        title: "What is the new branch name?"
        initialValue: ""
    command: "git spinoff {{index .PromptResponses 0}}"
    context: "localBranches"
    loadingText: "Creating branch"
  - key: "o"
    description: "open pull request in browser"
    command: "gh pr view --web"
    context: "localBranches"
    loadingText: "Opening pull request"
  - key: "C"
    description: "create pull request in browser"
    command: "gh pr create --web"
    context: "localBranches"
    loadingText: "Opening browser"
  - key: "y"
    description: "copy pull request URL to clipboard"
    command: "gh pr view {{.SelectedLocalBranch.Name}} --json url | jq '.url' | tr -d '\"' | pbcopy"
    context: "localBranches"
    loadingText: "Copying PR URL"
