#!/bin/bash
BRANCH_NAME=$(git symbolic-ref HEAD | xargs)
BRANCH_REGEX="[--|__]([0-9]+)"
COMMIT_EDITMSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_EDITMSG_FILE)

if [[ $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
    STORY_ID=${BASH_REMATCH[1]}
    if [[ $COMMIT_MSG =~ $STORY_ID ]]; then
        exit
    fi
    printf "\n\n[https://www.pivotaltracker.com/story/show/$STORY_ID]" >> $COMMIT_EDITMSG_FILE
fi
